name: PublicDummy0815
favicon: null
layout_spectrum: 0.3415859790984541
typography_spectrum: 0.9086126012261957
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.9403573437593877
  lightness: 0.3308872792404145
  saturation: 0.5574394292198122
  rhythmicContrast: 0.08523844461888075
purpose: []
